###
POST http://localhost:3000/subscribe
Content-Type: application/json
Authorization: Bearer {{$dotenv API_KEYS}}

{
    "phone": "4087977416"
}

###
GET http://localhost:3000/users
Authorization: Bearer {{$dotenv API_KEYS}}

###
GET http://localhost:3000/messages
Authorization: Bearer {{$dotenv API_KEYS}}

###
GET http://localhost:3000/messages/+14087977416
Authorization: Bearer {{$dotenv API_KEYS}}

###
POST http://localhost:3000/send
Content-Type: application/json
Authorization: Bearer {{$dotenv API_KEYS}}

{
    "message": "🚽 Gotta piss? Need a snack? Feel free to leave during intermission and get notified when the next set starts: https://madebycounter.com/notify"
}